[package]
name = "clauro-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clauro-core = { path = "../clauro-core" }
reqwest = { version = "0.13.1", default-features = false, features = ["rustls", "webpki-roots", "json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
